# Generated by Django 3.2.7 on 2024-08-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_chip_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pot_size',
            field=models.IntegerField(default=0),
        ),
    ]
