# Generated by Django 3.2.7 on 2024-08-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_pot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='card1',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='card2',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='card3',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='card4',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='card5',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card1',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card2',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
