# Generated by Django 3.2.7 on 2024-08-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hand_strength',
            field=models.IntegerField(default=0),
        ),
    ]
