# Generated by Django 3.2.7 on 2024-09-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_hand_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bot_card1',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='bot_card2',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
