# Generated by Django 3.2.7 on 2024-09-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20240901_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bot_chip_count',
            field=models.IntegerField(default=5000),
        ),
    ]
