# Generated by Django 3.2.7 on 2024-09-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_room_bot_chip_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bot_hand_strength',
            field=models.IntegerField(default=0),
        ),
    ]
